### ISSUE TITLE
compile error using VS2019

### ISSUE THREAD

**Issue by spacejumpunreal** [Ubpa/USRefl#1]
tried compiling the example, and got these errors, I am using c++lastest :
[TryReflCpp.zip](https://github.com/Ubpa/USRefl/files/4912559/TryReflCpp.zip)

1>------ Build started: Project: TryReflCpp, Configuration: Debug x64 ------
1>TryReflCpp.cpp
1>C:\try\cpp\TryReflCpp\USRefl.h(21,22): error C2760: syntax error: unexpected token ')', expected 'expression'
1>C:\try\cpp\TryReflCpp\USRefl.h(28,36): error C2760: syntax error: unexpected token ')', expected 'expression'
1>C:\try\cpp\TryReflCpp\TryReflCpp.cpp(8,10): warning C5030: attribute 'size' is not recognized
1>C:\try\cpp\TryReflCpp\TryReflCpp.cpp(9,7): warning C5030: attribute 'not_serialize' is not recognized
1>C:\try\cpp\TryReflCpp\TryReflCpp.cpp(11,7): warning C5030: attribute 'info' is not recognized
1>C:\try\cpp\TryReflCpp\TryReflCpp.cpp(40,30): error C2653: 'Type': is not a class or namespace name
1>C:\try\cpp\TryReflCpp\TryReflCpp.cpp(40,38): error C2903: 'Type': symbol is neither a class template nor a function template
1>C:\try\cpp\TryReflCpp\TryReflCpp.cpp(40,32): error C2065: 'fields': undeclared identifier
1>Done building project "TryReflCpp.vcxproj" -- FAILED.

**Comment by Ubpa** [comment]
I fix the bugs, try again. (I changed USRefl.h and the example in README)
// In addition, you can disable warning C5030 by `#pragma warning( disable : 5030 )`
